"""Database schema definitions."""

# Explicit column list — excludes raw JSON blobs
SNAPSHOT_COLUMNS = [
    "id",
    "recorded_at",
    "ctl",
    "atl",
    "tsb",
    "ramp_rate",
    "ac_ratio",
    "resting_hr",
    "hrv",
    "hrv_sdnn",
    "sleep_secs",
    "sleep_quality",
    "rest_days",
    "monotony",
    "training_strain",
    "vo2max",
    "sleep_score",
    "steps",
    "spo2",
    "stress",
    "readiness",
    "weight",
    "body_fat",
    "mood",
    "motivation",
    "fatigue",
    "soreness",
    "comments",
    "elevation_gain_m",
    "avg_cadence",
    "max_hr",
    "hr_zone_z1_secs",
    "hr_zone_z2_secs",
    "hr_zone_z3_secs",
    "hr_zone_z4_secs",
    "hr_zone_z5_secs",
    "icu_rpe",
    "feel",
    "critical_speed",
    "d_prime",
    "total_distance_km",
    "run_count",
    "longest_run_km",
    "avg_pace",
    "week_0_km",
    "week_1_km",
    "week_2_km",
    "week_3_km",
    "week_4_km",
    "last_month_km",
    "longest_streak",
    "longest_streak_date",
    "longest_break_days",
    "longest_break_date",
    "avg_days_run_per_week",
    "days_run_am",
    "days_run_pm",
    "days_run_both",
    "most_often_run_day",
    "weather_temp",
    "weather_temp_feels_like",
    "weather_humidity",
    "weather_wind_speed",
    "weather_type",
    "strava_weekly_km",
    "strava_total_km",
    "strava_run_count",
    "strava_ytd_km",
]

# Schema migrations - columns added over time
MIGRATIONS = [
    ("week_0_km", "REAL"),
    ("critical_speed", "REAL"),
    ("d_prime", "REAL"),
    # Wellness fields
    ("hrv_sdnn", "REAL"),
    ("stress", "REAL"),
    ("readiness", "REAL"),
    ("weight", "REAL"),
    ("body_fat", "REAL"),
    ("mood", "INTEGER"),
    ("motivation", "INTEGER"),
    ("fatigue", "INTEGER"),
    ("soreness", "INTEGER"),
    ("comments", "TEXT"),
    # Activity metrics
    ("elevation_gain_m", "REAL"),
    ("avg_cadence", "REAL"),
    ("max_hr", "INTEGER"),
    ("hr_zone_z1_secs", "INTEGER"),
    ("hr_zone_z2_secs", "INTEGER"),
    ("hr_zone_z3_secs", "INTEGER"),
    ("hr_zone_z4_secs", "INTEGER"),
    ("hr_zone_z5_secs", "INTEGER"),
    ("icu_rpe", "INTEGER"),
    ("feel", "INTEGER"),
    # Smashrun stats
    ("longest_streak", "INTEGER"),
    ("longest_streak_date", "TEXT"),
    ("longest_break_days", "INTEGER"),
    ("longest_break_date", "TEXT"),
    ("avg_days_run_per_week", "REAL"),
    ("days_run_am", "INTEGER"),
    ("days_run_pm", "INTEGER"),
    ("days_run_both", "INTEGER"),
    ("most_often_run_day", "TEXT"),
    # Weather
    ("weather_temp", "REAL"),
    ("weather_temp_feels_like", "REAL"),
    ("weather_humidity", "INTEGER"),
    ("weather_wind_speed", "REAL"),
    ("weather_type", "TEXT"),
    # Strava
    ("strava_weekly_km", "REAL"),
    ("strava_total_km", "REAL"),
    ("strava_run_count", "INTEGER"),
    ("strava_ytd_km", "REAL"),
]

CREATE_PERSONAL_RECORDS_TABLE = """
    CREATE TABLE IF NOT EXISTS personal_records (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        detected_at     TEXT NOT NULL,
        distance_label  TEXT NOT NULL UNIQUE,
        distance_m      INTEGER NOT NULL,
        time_secs       REAL NOT NULL,
        pace_str        TEXT NOT NULL,
        activity_date   TEXT NOT NULL,
        activity_id     TEXT
    )
"""

CREATE_TRAINING_NOTES_TABLE = """
    CREATE TABLE IF NOT EXISTS training_notes (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        created_at  TEXT NOT NULL,
        note_date   TEXT NOT NULL,
        content     TEXT NOT NULL
    )
"""

CREATE_GOALS_TABLE = """
    CREATE TABLE IF NOT EXISTS goals (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        created_at      TEXT NOT NULL,
        goal_type       TEXT NOT NULL,
        target_value    REAL NOT NULL,
        period_start    TEXT,
        is_active       INTEGER DEFAULT 1
    )
"""

CREATE_SNAPSHOTS_TABLE = """
    CREATE TABLE IF NOT EXISTS snapshots (
        id               INTEGER PRIMARY KEY AUTOINCREMENT,
        recorded_at      TEXT NOT NULL,
        ctl              REAL,
        atl              REAL,
        tsb              REAL,
        ramp_rate        REAL,
        ac_ratio         REAL,
        resting_hr       INTEGER,
        hrv              REAL,
        hrv_sdnn         REAL,
        sleep_secs       INTEGER,
        sleep_quality    INTEGER,
        rest_days        INTEGER,
        monotony         REAL,
        training_strain  REAL,
        vo2max           REAL,
        sleep_score      REAL,
        steps            INTEGER,
        spo2             REAL,
        stress           REAL,
        readiness        REAL,
        weight           REAL,
        body_fat         REAL,
        mood             INTEGER,
        motivation       INTEGER,
        fatigue          INTEGER,
        soreness         INTEGER,
        comments         TEXT,
        elevation_gain_m      REAL,
        avg_cadence           REAL,
        max_hr                INTEGER,
        hr_zone_z1_secs       INTEGER,
        hr_zone_z2_secs       INTEGER,
        hr_zone_z3_secs       INTEGER,
        hr_zone_z4_secs       INTEGER,
        hr_zone_z5_secs       INTEGER,
        icu_rpe               INTEGER,
        feel                  INTEGER,
        critical_speed   REAL,
        d_prime          REAL,
        total_distance_km  REAL,
        run_count          INTEGER,
        longest_run_km     REAL,
        avg_pace           TEXT,
        week_0_km          REAL,
        week_1_km          REAL,
        week_2_km          REAL,
        week_3_km          REAL,
        week_4_km          REAL,
        last_month_km      REAL,
        longest_streak         INTEGER,
        longest_streak_date    TEXT,
        longest_break_days     INTEGER,
        longest_break_date     TEXT,
        avg_days_run_per_week  REAL,
        days_run_am            INTEGER,
        days_run_pm            INTEGER,
        days_run_both          INTEGER,
        most_often_run_day     TEXT,
        weather_temp           REAL,
        weather_temp_feels_like REAL,
        weather_humidity       INTEGER,
        weather_wind_speed     REAL,
        weather_type           TEXT,
        strava_weekly_km       REAL,
        strava_total_km        REAL,
        strava_run_count       INTEGER,
        strava_ytd_km          REAL,
        intervals_json   TEXT,
        smashrun_json    TEXT
    )
"""

INSERT_SNAPSHOT = """
    INSERT INTO snapshots (
        recorded_at,
        ctl, atl, tsb, ramp_rate, ac_ratio,
        resting_hr, hrv, hrv_sdnn, sleep_secs, sleep_quality,
        rest_days, monotony, training_strain,
        vo2max, sleep_score, steps, spo2,
        stress, readiness, weight, body_fat,
        mood, motivation, fatigue, soreness, comments,
        elevation_gain_m, avg_cadence, max_hr,
        hr_zone_z1_secs, hr_zone_z2_secs, hr_zone_z3_secs, hr_zone_z4_secs, hr_zone_z5_secs,
        icu_rpe, feel,
        critical_speed, d_prime,
        total_distance_km, run_count, longest_run_km, avg_pace,
        week_0_km, week_1_km, week_2_km, week_3_km, week_4_km, last_month_km,
        longest_streak, longest_streak_date, longest_break_days, longest_break_date,
        avg_days_run_per_week, days_run_am, days_run_pm, days_run_both, most_often_run_day,
        weather_temp, weather_temp_feels_like, weather_humidity, weather_wind_speed, weather_type,
        strava_weekly_km, strava_total_km, strava_run_count, strava_ytd_km,
        intervals_json, smashrun_json
    ) VALUES (
        :recorded_at,
        :ctl, :atl, :tsb, :ramp_rate, :ac_ratio,
        :resting_hr, :hrv, :hrv_sdnn, :sleep_secs, :sleep_quality,
        :rest_days, :monotony, :training_strain,
        :vo2max, :sleep_score, :steps, :spo2,
        :stress, :readiness, :weight, :body_fat,
        :mood, :motivation, :fatigue, :soreness, :comments,
        :elevation_gain_m, :avg_cadence, :max_hr,
        :hr_zone_z1_secs, :hr_zone_z2_secs, :hr_zone_z3_secs, :hr_zone_z4_secs, :hr_zone_z5_secs,
        :icu_rpe, :feel,
        :critical_speed, :d_prime,
        :total_distance_km, :run_count, :longest_run_km, :avg_pace,
        :week_0_km, :week_1_km, :week_2_km, :week_3_km, :week_4_km, :last_month_km,
        :longest_streak, :longest_streak_date, :longest_break_days, :longest_break_date,
        :avg_days_run_per_week, :days_run_am, :days_run_pm, :days_run_both, :most_often_run_day,
        :weather_temp, :weather_temp_feels_like, :weather_humidity,
        :weather_wind_speed, :weather_type,
        :strava_weekly_km, :strava_total_km, :strava_run_count, :strava_ytd_km,
        :intervals_json, :smashrun_json
    )
"""
